name: "LogicSuite"
version: '${project.version}'
main: de.frinshhd.logicsuite.Main
api-version: '1.20'
authors:
  - FrinshHD

permissions:
  logicsuite.night:
    default: op
  logicsuite.day:
    default: op
  logicsuite.gamemode:
    default: op
  logicsuite.teleport:
    default: op
  logicsuite.main:
    default: op
  logicsuite.weather:
    default: op
  logicsuite.chat:
    default: op